const { Vendor } = require('../models')

// role seeds
module.exports = async () => {
  await Vendor.bulkCreate([
    { vendorId: 283, name: 'A M LEONARD INC'.trim() },
    { vendorId: 248, name: 'A-1 EXTERMINATING CO INC'.trim() },
    { vendorId: 258, name: 'ABT  INC'.trim() },
    { vendorId: 427, name: 'ACE ADVENTURE RESORT'.trim() },
    { vendorId: 439, name: 'ACE HARDWARE CENTER'.trim() },
    { vendorId: 56897, name: 'ACE PIPELINE'.trim() },
    { vendorId: 33161, name: 'ADAM CHEESEMAN'.trim() },
    { vendorId: 287, name: 'ADVANTAGE OCCUPATIONAL'.trim() },
    { vendorId: 464, name: 'ADVANTAGE TECHNOLOGY LLC'.trim() },
    { vendorId: 1030, name: 'ALMOST HEAVEN KONA ICE LLC'.trim() },
    { vendorId: 1047, name: 'ALTITUDE LEARNING'.trim() },
    { vendorId: 37201, name: 'AMANDA BRIDGETTE'.trim() },
    { vendorId: 15540, name: 'AMANDA GUM'.trim() },
    { vendorId: 31316, name: 'AMANDA RICHARDS'.trim() },
    { vendorId: 33381, name: 'AMANDA TRENT'.trim() },
    { vendorId: 1043, name: 'AMAZON.COM'.trim() },
    { vendorId: 1250, name: 'AMERICAN BENEFIT CORPORATION'.trim() },
    { vendorId: 1570, name: 'AMERICAN RED CROSS'.trim() },
    { vendorId: 1631, name: 'AMTOWER AUTO PARTS'.trim() },
    { vendorId: 1647, name: 'ANDERSON EXCAVATING LLC'.trim() },
    { vendorId: 8695, name: 'ANGELA CURRAN'.trim() },
    { vendorId: 8694, name: 'ANGELA K. BAILES'.trim() },
    { vendorId: 36169, name: 'ANGELA SUMMERS'.trim() },
    { vendorId: 1685, name: 'APPALACHIAN COUNCIL HEAD START'.trim() },
    { vendorId: 1754, name: ' APPLE INC'.trim() },
    { vendorId: 1750, name: 'APPLE STORE FOR EDUCATION INST'.trim() },
    { vendorId: 1752, name: 'APPLIED EDUCATION SYSTEMS'.trim() },
    { vendorId: 1759, name: 'AQUA FILTER FRESH INC'.trim() },
    { vendorId: 1768, name: 'ARMSTRONG'.trim() },
    { vendorId: 1965, name: 'ATCO INTERNATIONAL'.trim() },
    { vendorId: 50, name: 'AXA EQUITABLE'.trim() },
    { vendorId: 2500, name: 'BANDLAND  LLC'.trim() },
    { vendorId: 37071, name: 'BENJAMIN THOMAS'.trim() },
    { vendorId: 2994, name: 'BEST LIFE THERAPY LLC'.trim() },
    { vendorId: 32332, name: 'BEST ONE TIRE (DBA)'.trim() },
    { vendorId: 27490, name: 'BETSY WELLS'.trim() },
    { vendorId: 3241, name: 'BIG ASS HOLDING  LLC'.trim() },
    { vendorId: 3330, name: 'BIO CORPORATION'.trim() },
    { vendorId: 4007, name: 'BRIDGEPORT EXPRESS CARE'.trim() },
    { vendorId: 4275, name: 'BROOKE SMOLDER'.trim() },
    { vendorId: 4410, name: 'BSN SPORTS'.trim() },
    { vendorId: 4681, name: 'BULLDOG TIRE AND AUTO CENTER'.trim() },
    { vendorId: 39493, name: 'CAITLYN WALKER'.trim() },
    { vendorId: 5565, name: 'CAROLINA BIOLOGICAL SUPPLY CO'.trim() },
    { vendorId: 88774, name: 'CASEY MOORE'.trim() },
    { vendorId: 5615, name: 'CEDAR LAKES CONFERENCE CENTER'.trim() },
    { vendorId: 12760, name: 'CHAD EVANS'.trim() },
    { vendorId: 6050, name: 'CHANGEPOINT LEARNING LLC'.trim() },
    { vendorId: 37170, name: 'CHARLES A TITUS'.trim() },
    { vendorId: 23280, name: 'CHELSEA LOPEZ'.trim() },
    { vendorId: 6995, name: 'CHRISTOPHER COFFMAN'.trim() },
    { vendorId: 12466, name: 'CHRISTOPHER RYAN ADKINS'.trim() },
    { vendorId: 32447, name: 'CINTAS'.trim() },
    { vendorId: 6526, name: 'CITY CONSTRUCTION CO DBA'.trim() },
    { vendorId: 6521, name: 'CITY CONSTRUCTION COMPANY  INC'.trim() },
    { vendorId: 6902, name: 'CLASSLINK'.trim() },
    { vendorId: 5240, name: 'CNA SURETY'.trim() },
    { vendorId: 7152, name: 'COLONIAL SPECIALTY & FLAG CO'.trim() },
    { vendorId: 7300, name: 'COLUMBUS ZOO & AQUARIUM'.trim() },
    { vendorId: 7600, name: 'COMTECH'.trim() },
    { vendorId: 2, name: 'CORNERSTONE BANK'.trim() },
    { vendorId: 9757, name: 'COURTNEY DEAN'.trim() },
    { vendorId: 9758, name: 'COURTNEY MCCARTNEY'.trim() },
    { vendorId: 50072, name: 'CRAIG KELLAR'.trim() },
    { vendorId: 21151, name: 'CRAIG MIGLIACCIO'.trim() },
    { vendorId: 8599, name: 'CRISIS PREVENTION INSTITUTE CP'.trim() },
    { vendorId: 8763, name: 'CUSTOM INK'.trim() },
    { vendorId: 8776, name: 'CWS OFFICE SOLUTIONS'.trim() },
    { vendorId: 8775, name: 'CWS  INC'.trim() },
    { vendorId: 8803, name: 'CYBERSOFT TECHNOLOGIES'.trim() },
    { vendorId: 23764, name: 'DARREN MCCULLOUGH'.trim() },
    { vendorId: 19876, name: 'DAVID B SANDRIDGE'.trim() },
    { vendorId: 9607, name: 'DAVIS ATHLETICS LLC'.trim() },
    { vendorId: 12762, name: 'DAWSON EVANS'.trim() },
    { vendorId: 9752, name: 'DEMOULIN BROTHERS & COMPANY'.trim() },
    { vendorId: 4797, name: 'DENVER LEE BURNSIDE'.trim() },
    { vendorId: 9842, name: 'DEPARTMENT OF TRANSPORTATION'.trim() },
    { vendorId: 3, name: 'DEPT. OF TAX AND REVENUE'.trim() },
    { vendorId: 10085, name: 'DIDAX'.trim() },
    { vendorId: 10100, name: 'DIESEL LAPTOPS LLC'.trim() },
    { vendorId: 10130, name: 'DINSMORE & SHOHL LLP'.trim() },
    { vendorId: 10275, name: 'DISCOUNT SCHOOL SUPPLY'.trim() },
    { vendorId: 10400, name: 'DODDRIDGE CO BD OF EDUCATION'.trim() },
    { vendorId: 10433, name: 'DODDRIDGE CO ELEMENTARY SCHOOL'.trim() },
    { vendorId: 10410, name: 'DODDRIDGE COUNTY BOARD OF ED'.trim() },
    { vendorId: 10700, name: 'DODDRIDGE COUNTY HEALTH DEPT'.trim() },
    { vendorId: 10474, name: 'DODDRIDGE COUNTY HIGH SCHOOL'.trim() },
    { vendorId: 10485, name: 'DODDRIDGE COUNTY MIDDLE SCHOOL'.trim() },
    { vendorId: 10900, name: 'DODDRIDGE INDEPENDENT'.trim() },
    { vendorId: 18300, name: 'DOMINION ENERGY WEST VIRGINIA'.trim() },
    { vendorId: 33221, name: 'DONNA L SIMMONS'.trim() },
    { vendorId: 31910, name: 'DONNA MICHELLE ROBEY'.trim() },
    { vendorId: 11341, name: 'DST INNOVATIONS'.trim() },
    { vendorId: 11559, name: 'DURBIN & GREENBIER VALLEY RAIL'.trim() },
    { vendorId: 11381, name: 'DYNAMIC DEVELOPMENT INC'.trim() },
    { vendorId: 11920, name: 'EDGENUITY  INC'.trim() },
    { vendorId: 12100, name: 'EDPUZZLE'.trim() },
    { vendorId: 14246, name: 'EDUSPIRE SOLUTIONS'.trim() },
    { vendorId: 4004, name: 'ENCOVA INSURANCE'.trim() },
    { vendorId: 12577, name: 'ENVIROCLEAN LLC'.trim() },
    { vendorId: 12722, name: 'EQUIPARTS CORP'.trim() },
    { vendorId: 12565, name: 'ESPECIAL NEEDS.COM'.trim() },
    { vendorId: 12770, name: 'EVANS CONSTRUCTION'.trim() },
    { vendorId: 13106, name: 'FAIRMONT STATE UNIVERSITY'.trim() },
    { vendorId: 13125, name: 'FAIRVIEW DINER'.trim() },
    { vendorId: 13140, name: 'FBLA-PBL INC'.trim() },
    { vendorId: 13188, name: 'FIELDTURF USA  INC'.trim() },
    { vendorId: 13190, name: 'FIFTH THIRD BANK'.trim() },
    { vendorId: 44558, name: 'FOLLETT HIGHER EDUCATION GROUP'.trim() },
    { vendorId: 13348, name: 'FOLLETT SCHOOL SOLUTIONS  INC'.trim() },
    { vendorId: 13350, name: 'FOLLETT SOFTWARE CO'.trim() },
    { vendorId: 13859, name: 'FRONTIER COMMUNICATIONS'.trim() },
    { vendorId: 13899, name: 'FUN.COM  INC'.trim() },
    { vendorId: 41224, name: 'FUTURE BUSINESS LEADERS OF AME'.trim() },
    { vendorId: 14204, name: 'GENERATION GENIUS INC'.trim() },
    { vendorId: 43262, name: 'GEORGE L WILSON & CO'.trim() },
    { vendorId: 14395, name: 'GLENVILLE STATE COLLEGE'.trim() },
    { vendorId: 14401, name: 'GLOBAL INDUSTRIAL EQUIPMENT'.trim() },
    { vendorId: 14520, name: 'GOODHEART-WILCOX PUBLISHERS'.trim() },
    { vendorId: 14554, name: 'GOPHER SPORTS EQUIPMENT'.trim() },
    { vendorId: 14568, name: 'GORDON FOOD SERIVCE  INC.'.trim() },
    { vendorId: 14570, name: 'GORDON STOWE & ASSOCIATES'.trim() },
    { vendorId: 14865, name: 'GRAINGER'.trim() },
    { vendorId: 15014, name: 'GREAT MINDS PBC'.trim() },
    { vendorId: 3776, name: 'GREGORY D BONNELL'.trim() },
    { vendorId: 15574, name: 'GUTTMAN OIL COMPANY'.trim() },
    { vendorId: 15624, name: "HALL'S FEED & FARM SUPPLY".trim() },
    { vendorId: 16100, name: 'HARRISON RURAL'.trim() },
    { vendorId: 15200, name: 'HARRY GREEN CHEVROLET  INC'.trim() },
    { vendorId: 16439, name: 'HAYES SOFTWARE SYSTEM'.trim() },
    { vendorId: 16800, name: 'HERALD RECORD LLC'.trim() },
    { vendorId: 17175, name: 'HILLYARD OHIO'.trim() },
    { vendorId: 18181, name: 'HOMESTEAD FARM CENTER'.trim() },
    { vendorId: 18401, name: 'HOUGHTON MIFFLIN HARCOURT'.trim() },
    { vendorId: 18430, name: 'HPS  LLC'.trim() },
    { vendorId: 18455, name: 'HUBERT COMPANY'.trim() },
    { vendorId: 18804, name: 'ICEV'.trim() },
    { vendorId: 18818, name: 'IDVILLE'.trim() },
    { vendorId: 19020, name: 'INFOBASE'.trim() },
    { vendorId: 19061, name: 'INTEGRATED SPEECH SOLUTIONS'.trim() },
    { vendorId: 19095, name: 'INTERNAL REVENUE SERVICE'.trim() },
    { vendorId: 19070, name: 'INTERSTATE BATTERY'.trim() },
    { vendorId: 19131, name: 'INTRADO INTERACIVE SERVICES CO'.trim() },
    { vendorId: 19202, name: 'IT SAVVY  LLC'.trim() },
    { vendorId: 19220, name: 'IXL LEARNING'.trim() },
    { vendorId: 19298, name: 'J P SERVICE STATION'.trim() },
    { vendorId: 20697, name: 'J W PEPPER & SONS  INC'.trim() },
    { vendorId: 30973, name: 'JACOB RABEL'.trim() },
    { vendorId: 16920, name: 'JACQUELINE J HETZER'.trim() },
    { vendorId: 22053, name: 'JAMES LAMBERT'.trim() },
    { vendorId: 77451, name: "JANN'S NETCRAFT  LLC".trim() },
    { vendorId: 18810, name: 'JARAD ICE'.trim() },
    { vendorId: 29775, name: 'JASON POWERS'.trim() },
    { vendorId: 16386, name: 'JEFF HAUGHT'.trim() },
    { vendorId: 19805, name: 'JENKINS AUTO'.trim() },
    { vendorId: 22732, name: 'JENNIFER LEGGETT'.trim() },
    { vendorId: 39720, name: 'JEREMY WAUGAMAN'.trim() },
    { vendorId: 5689, name: 'JEROME M SATTLER PUBLISHER '.trim() },
    { vendorId: 26890, name: 'JILL MYERS'.trim() },
    { vendorId: 5656, name: "JOHNNY'S SELECTED SEEDS".trim() },
    { vendorId: 32010, name: 'JUDITH A ROBINSON'.trim() },
    { vendorId: 10998, name: 'JUSTIN HOLTZ'.trim() },
    { vendorId: 20751, name: 'KAJEET'.trim() },
    { vendorId: 10999, name: 'KALEIGH DOTSON'.trim() },
    { vendorId: 20770, name: 'KAPLAN SCHOOL SUPPLY'.trim() },
    { vendorId: 12475, name: 'KATHERINE J ELLIFRITT'.trim() },
    { vendorId: 42230, name: 'KATRINA WHITE'.trim() },
    { vendorId: 21315, name: 'KELLY GENERATOR & EQUIPMENT'.trim() },
    { vendorId: 16625, name: 'KENNETH HEINEY'.trim() },
    { vendorId: 21395, name: 'KENNYWOOD'.trim() },
    { vendorId: 21500, name: 'KICKAPPS LLC'.trim() },
    { vendorId: 499, name: 'KIMBERLY AHOUSE'.trim() },
    { vendorId: 21988, name: 'KIMBERLY SUTTON'.trim() },
    { vendorId: 21857, name: 'KONA ICE OF MID OHIO VALLEY'.trim() },
    { vendorId: 9811, name: 'KYRIE DEMOSS'.trim() },
    { vendorId: 20719, name: 'K2SHARE  LLC'.trim() },
    { vendorId: 21995, name: 'LAKESHORE LEARNING MATERIALS'.trim() },
    { vendorId: 14320, name: 'LARESSA GLASPELL'.trim() },
    { vendorId: 7888, name: 'LAURA M COTTRILL'.trim() },
    { vendorId: 22200, name: 'LAWSON PRODUCTS INC'.trim() },
    { vendorId: 22123, name: 'LEARNIX  LLC'.trim() },
    { vendorId: 22718, name: 'LEEDY ELEVATOR INSPECTION'.trim() },
    { vendorId: 19689, name: 'LIBBY JAROM'.trim() },
    { vendorId: 22895, name: 'LIBERTY UNIVERSITY'.trim() },
    { vendorId: 23024, name: 'LIFE STUDIES LLC'.trim() },
    { vendorId: 34000, name: 'LISA STAFFORD'.trim() },
    { vendorId: 36840, name: 'ISA TALKINGTON'.trim() },
    { vendorId: 23207, name: 'LITERACY RESOURCES'.trim() },
    { vendorId: 23219, name: 'LIVE STOCK JUDGING'.trim() },
    { vendorId: 23222, name: "LLOYD'S ELECTRONICS".trim() },
    { vendorId: 23325, name: 'LOWES HOME IMPROVEMENT'.trim() },
    { vendorId: 24456, name: 'MARION CO BOARD OF EDUCATION'.trim() },
    { vendorId: 24325, name: 'MAS SERVICE CO'.trim() },
    { vendorId: 24790, name: 'MATH AND MUSCLE LLC'.trim() },
    { vendorId: 24800, name: 'MATHENY MOTOR TRUCK CO'.trim() },
    { vendorId: 62, name: 'MATRIX TRUST COMPANY'.trim() },
    { vendorId: 606, name: 'MATTHEW ALEXANDER'.trim() },
    { vendorId: 24824, name: 'MAY BROTHERS COMPANY'.trim() },
    { vendorId: 23905, name: 'MCGRAW-HILL EDUCATION'.trim() },
    { vendorId: 24909, name: 'MEASUREMENT INCORPORATED'.trim() },
    { vendorId: 24935, name: 'MEDEXPRESS'.trim() },
    { vendorId: 25583, name: 'MIDWEST MOTOR SUPPLY CO INC'.trim() },
    { vendorId: 25610, name: 'MILESTONES AND MUSIC'.trim() },
    { vendorId: 50008, name: 'MIRANDA MITCHELL'.trim() },
    { vendorId: 25755, name: 'MON POWER'.trim() },
    { vendorId: 88775, name: 'MONICA ROBINSON'.trim() },
    { vendorId: 26590, name: 'MOUNTAIN VIEW VINYL'.trim() },
    { vendorId: 26630, name: 'MPE RENTALS'.trim() },
    { vendorId: 27000, name: 'NASCO'.trim() },
    { vendorId: 27326, name: 'NATIONAL FFA ORGANIZATION'.trim() },
    { vendorId: 27110, name: 'NCS PEARSON'.trim() },
    { vendorId: 27482, name: 'NEOLA INC'.trim() },
    { vendorId: 27502, name: 'NETSUPPORT INCORPORATED'.trim() },
    { vendorId: 27522, name: 'NEW ENGLAND SECURITY LOCK CO'.trim() },
    { vendorId: 27735, name: 'NITRO CONSTRUCTION SERVICES'.trim() },
    { vendorId: 27750, name: 'NOLL FEED & HARDWARE'.trim() },
    { vendorId: 19430, name: 'NORMAN JACKSON TRUCKING INC'.trim() },
    { vendorId: 27795, name: 'NORTH BEND OUTFITTERS'.trim() },
    { vendorId: 27837, name: 'NORTHWEST EVALUATION ASSOC'.trim() },
    { vendorId: 28302, name: 'OSCAR F HENREY COMPANY'.trim() },
    { vendorId: 29978, name: 'OVERNIGHTGEEK COMPANIES'.trim() },
    { vendorId: 28760, name: 'PA TURNPIKE TOLL BY PLATE'.trim() },
    { vendorId: 28606, name: 'PARENT INSTITUTE'.trim() },
    { vendorId: 28613, name: 'PARK WAREHOUSE LLC'.trim() },
    { vendorId: 12425, name: 'PAULA LANG'.trim() },
    { vendorId: 28788, name: 'PEARSON CLINICAL ASSESSMENTS'.trim() },
    { vendorId: 12700, name: 'PEOPLES'.trim() },
    { vendorId: 29603, name: 'PIERPONT COMMUNITY & TECHNICAL'.trim() },
    { vendorId: 29650, name: 'PITNEY BOWES'.trim() },
    { vendorId: 29652, name: 'PITNEY BOWES GLOBAL FIN SVCS'.trim() },
    { vendorId: 29700, name: 'PIZZA HOUSE FAMILY RESTAURANT'.trim() },
    { vendorId: 29728, name: 'POWERSCHOOL GROUP LLC'.trim() },
    { vendorId: 29800, name: 'PRECISE CONNECTIONS'.trim() },
    { vendorId: 30240, name: 'PSYCHOLOGICAL ASSESSMENT'.trim() },
    { vendorId: 30800, name: 'QUILL CORPORATION'.trim() },
    { vendorId: 43275, name: 'R D WILSON & SONS'.trim() },
    { vendorId: 18474, name: 'R M HUFFMAN  INC'.trim() },
    { vendorId: 31017, name: 'RAM TOOL'.trim() },
    { vendorId: 31085, name: 'REALLY GOOD STUFF'.trim() },
    { vendorId: 31254, name: 'REFERENCE SERVICES INC'.trim() },
    { vendorId: 31121, name: 'REICHERT SPICE COMPANY'.trim() },
    { vendorId: 58, name: 'RELIASTAR LIFE INSURANCE CO'.trim() },
    { vendorId: 454, name: 'RENAISSANCE LEARNING  INC'.trim() },
    { vendorId: 31298, name: 'RESPONDUS INC'.trim() },
    { vendorId: 31297, name: 'RESTAURANT EQUIPPERS'.trim() },
    { vendorId: 31299, name: 'RETHINK AUTISM'.trim() },
    { vendorId: 31313, name: "RICH'S FARM  INC".trim() },
    { vendorId: 31455, name: 'RICHARDS AND SONS LLC'.trim() },
    { vendorId: 4450, name: 'ROBOTLAB INC.'.trim() },
    { vendorId: 27225, name: 'ROCHESTER 100 LLC'.trim() },
    { vendorId: 32119, name: 'ROSE HOLDINGS LLC'.trim() },
    { vendorId: 32339, name: 'SAFARI MONTAGE'.trim() },
    { vendorId: 32346, name: 'SAFETY RAIL'.trim() },
    { vendorId: 32345, name: 'SAFETY-KLEEN'.trim() },
    { vendorId: 32425, name: 'SALEM IGA MARKET'.trim() },
    { vendorId: 32438, name: "SAM'S CLUB".trim() },
    { vendorId: 21451, name: 'SANDRA KIMBALL'.trim() },
    { vendorId: 68899, name: 'SANDSTONE JETBOATS INC'.trim() },
    { vendorId: 32485, name: 'SCHINDLER ELEVATOR CORPORATION'.trim() },
    { vendorId: 32493, name: 'SCHOLASTIC MAGAZIES PUBLISHING'.trim() },
    { vendorId: 32490, name: 'SCHOLASTIC  INC'.trim() },
    { vendorId: 32508, name: 'SCHOOL CASH SUPPLIES'.trim() },
    { vendorId: 33015, name: 'SCHOOL OUTFITTERS LLC'.trim() },
    { vendorId: 12430, name: 'SCHOOL SPECIALTY INTERVENTION'.trim() },
    { vendorId: 33040, name: 'SCHOOL SPECIALTY LLC'.trim() },
    { vendorId: 31915, name: 'SCOTT ROBEY'.trim() },
    { vendorId: 33153, name: 'SECURITY VOICE INC'.trim() },
    { vendorId: 33147, name: 'SEESAW LEARNING INC'.trim() },
    { vendorId: 33217, name: 'SHARE CORP'.trim() },
    { vendorId: 13351, name: 'SHAYLYN DABBS'.trim() },
    { vendorId: 16600, name: 'SHERRY HECKERT'.trim() },
    { vendorId: 13370, name: 'SHOP & SAVE'.trim() },
    { vendorId: 33229, name: 'SIR SPEEDY'.trim() },
    { vendorId: 33297, name: 'SMART HORIZONS'.trim() },
    { vendorId: 33432, name: 'SMITH & SMITH HARDWOODS  INC.'.trim() },
    { vendorId: 34280, name: 'SOUTH HARRISON CHORAL BOOSTERS'.trim() },
    { vendorId: 34298, name: 'SOUTHERN EDUCATIONAL SERVICES'.trim() },
    { vendorId: 34517, name: 'SPARKLE JANITORIAL PRODUCTS'.trim() },
    { vendorId: 34534, name: 'SPECIALTY METAL SERVICES  INC'.trim() },
    { vendorId: 32315, name: 'SQUARE PANDA'.trim() },
    { vendorId: 34910, name: 'STAR WELD'.trim() },
    { vendorId: 34995, name: 'STATE BD OF RISK & INS MNGMT'.trim() },
    { vendorId: 35100, name: 'STATE ELECTRIC CO'.trim() },
    { vendorId: 35635, name: 'STENHOUSE PUBLISHERS'.trim() },
    { vendorId: 35631, name: 'STEPHANIE TAYLOR'.trim() },
    { vendorId: 36170, name: 'SUBSCRIPTION SVC OF AMERICA'.trim() },
    { vendorId: 36300, name: 'SUPERIOR INDUSTRIAL LAUNDRIES'.trim() },
    { vendorId: 33659, name: 'SURVEILLANCE-247 LLC'.trim() },
    { vendorId: 36685, name: 'SUTTLE & STALNAKER PLLC'.trim() },
    { vendorId: 36756, name: 'SWANK'.trim() },
    { vendorId: 21800, name: 'TAMMY S KNICELEY'.trim() },
    { vendorId: 36600, name: 'TAYLOR BROTHERS DOOR LOCK LLC'.trim() },
    { vendorId: 36744, name: 'TEACHER DIRECT'.trim() },
    { vendorId: 36753, name: 'TEACHER INNOVATIONS INC'.trim() },
    { vendorId: 36970, name: 'TEACHTOWN INC'.trim() },
    { vendorId: 6453, name: "THE CHILDREN'S HEALTH MARKET".trim() },
    { vendorId: 10975, name: 'THE DOLLYWOOD FOUNDATION'.trim() },
    { vendorId: 15215, name: 'THE GREENBRIER'.trim() },
    { vendorId: 125, name: 'THE HORACE MANN COMPANIES'.trim() },
    { vendorId: 55114, name: 'THE LAMPO GROUP  LLC'.trim() },
    { vendorId: 12558, name: 'THE LOST WORLD CAVERNS'.trim() },
    { vendorId: 28050, name: 'THE OP SHOP INC'.trim() },
    { vendorId: 55889, name: 'THE VINTAGE THEATRE COMPANY'.trim() },
    { vendorId: 43055, name: 'THE WILDS'.trim() },
    { vendorId: 37089, name: 'THRASHER GROUP  INC'.trim() },
    { vendorId: 15609, name: 'TIMOTHY HAHN'.trim() },
    { vendorId: 37635, name: 'TOTAL EQUIPMENT COMPANY'.trim() },
    { vendorId: 37800, name: 'TRACTOR SUPPLY COMPANY'.trim() },
    { vendorId: 37920, name: 'TRAVIS PHYSICAL THERAPY'.trim() },
    { vendorId: 37974, name: 'TRIBE INCLUSIVE LEARNING'.trim() },
    { vendorId: 38003, name: 'TRIPLE H ENTERPRISES INC'.trim() },
    { vendorId: 36827, name: 'TSA CONSULTING GROUP INC'.trim() },
    { vendorId: 38007, name: 'TURNITIN LLC'.trim() },
    { vendorId: 38022, name: 'TYGART VALLEY CINEMAS'.trim() },
    { vendorId: 38120, name: 'ULINE'.trim() },
    { vendorId: 38325, name: 'UNITED DAIRY INC'.trim() },
    { vendorId: 38369, name: 'UNITED RENTALS INC'.trim() },
    { vendorId: 38717, name: 'UNIVERSAL PUBLISHING'.trim() },
    { vendorId: 38880, name: 'VALLEY GEM'.trim() },
    { vendorId: 38963, name: 'VAPE EDUCATE LLC'.trim() },
    { vendorId: 2940, name: 'VERIZON WIRELESS'.trim() },
    { vendorId: 31047, name: 'VICTORIA RASTLE'.trim() },
    { vendorId: 9846, name: 'VITAL RECORDS'.trim() },
    { vendorId: 36813, name: 'VIVIAN L SWISHER'.trim() },
    { vendorId: 7701, name: 'WANETTA COLLINS'.trim() },
    { vendorId: 39651, name: 'WARDS NATURAL SCIENCE'.trim() },
    { vendorId: 40010, name: 'WEISSMAN THEATRICAL SUPPLY'.trim() },
    { vendorId: 40320, name: 'WESLEY EZELL'.trim() },
    { vendorId: 40380, name: 'WEST UNION  TOWN OF'.trim() },
    { vendorId: 33054, name: 'WEST VIRGINIA RETIREMENT PLUS'.trim() },
    { vendorId: 42150, name: 'WHALEY DISTRIBUTING CO'.trim() },
    { vendorId: 43128, name: 'WINFIELD HIGH SCHOOL'.trim() },
    { vendorId: 43155, name: 'WINSOR LEARNING'.trim() },
    { vendorId: 43404, name: ' WOODFORD OIL COMPANY'.trim() },
    { vendorId: 40554, name: 'WV ALL-STATE CHORUS'.trim() },
    { vendorId: 40616, name: 'WV CASE'.trim() },
    { vendorId: 40683, name: 'WV DEPARTMENT OF EDUCATION'.trim() },
    { vendorId: 40687, name: 'WV DEPARTMENT OF EDUCATION'.trim() },
    { vendorId: 41001, name: 'WV DEPT HEALTH & HUMAN RESRCS'.trim() },
    { vendorId: 40675, name: 'WV DEPT OF AGRICULTURE'.trim() },
    { vendorId: 41101, name: 'WV DEPT OF ENVIRON PROTECTION'.trim() },
    { vendorId: 41111, name: 'WV DIVISION OF LABOR'.trim() },
    { vendorId: 41112, name: 'WV DIVISION OF LABOR'.trim() },
    { vendorId: 41020, name: 'WV DIVISION OF MOTOR VEHICLES'.trim() },
    { vendorId: 41006, name: 'WV FFA ASSOCIATION'.trim() },
    { vendorId: 41270, name: 'WV SIGNAL & LIGHT INC'.trim() },
    { vendorId: 40609, name: 'WVASHRO  INC'.trim() },
    { vendorId: 41007, name: 'WVSPA'.trim() },
    { vendorId: 41018, name: 'WVU PARKERSBURG'.trim() },
    { vendorId: 37928, name: 'ZACHARY TRAVIS'.trim() },
    { vendorId: 36820, name: '2080 MEDIA INC'.trim() }
  ])
}
